# Generated by Django 5.2.5 on 2025-12-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0009_rename_college_user_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('college_admin', 'College Admin'), ('department_admin', 'Department Admin'), ('user', 'Student / User'), ('guest', 'Guest')], default='user', max_length=20),
        ),
    ]
