# Generated by Django 5.2.5 on 2025-12-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0010_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=10),
        ),
    ]
