# Generated by Django 5.2.5 on 2025-12-02 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0011_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
    ]
